### ISSUE TITLE
Duotone support

### ISSUE THREAD

**Issue by MaximVanhove** [husseinalhammad/FontAwesomeSVG-PHP#1]
Are there any plans to add duotone support?

**Comment by husseinalhammad** [comment]
Duotone support will certainly be nice and I'll be eager to support it. I need to take a closer look at this. I'll update this issue with any relevant details.

**Comment by husseinalhammad** [comment]
I've added duotone support to [v1.2-beta](https://github.com/husseinalhammad/FontAwesomeSVG-PHP/releases/tag/v1.2-beta). Refer to the [readme in the duotone branch](https://github.com/husseinalhammad/FontAwesomeSVG-PHP/tree/duotone) for usage instructions.

```php
echo $FA->get_svg('fad fa-laugh-wink', [
    'primary' => [
        'fill'    => '#e64980',
        'opacity' => '0.5',
    ],
    'secondary' => [
        'fill'    => '#fcc417',
        'opacity' => '1',
    ],
]);
```


I'll keep the issue open until v1.2 is released.

**Comment by MaximVanhove** [comment]
Works like a charm!
