### ISSUE TITLE
Set a license

### ISSUE THREAD

**Issue by fabianmossberg** [husseinalhammad/FontAwesomeSVG-PHP#3]
This is a nice project, but it's currently unlicensed.

It would be nice if you could set a license for it so we know if it's something we can use or not.

**Comment by husseinalhammad** [comment]
Thanks, @fabianmossberg. Good point. I'll add one soonish.

**Comment by husseinalhammad** [comment]
Thanks for your patience, @fabianmossberg. A license has been added: https://github.com/husseinalhammad/FontAwesomeSVG-PHP/blob/master/LICENSE
